import type { Camera } from "@babylonjs/core/Cameras/camera";
import type { Scene } from "@babylonjs/core/scene";
/**
 * SE-02: Screen-space bilateral normal smooth post-process.
 * Detects cube face boundaries via 3×3 normal divergence and blends colour
 * at voxel edges using a 5×5 bilateral filter weighted by normal similarity
 * and depth proximity. Reads the PrePassRenderer G-buffer generated by SSAO2
 * (zero extra G-buffer cost).
 *
 * Must be constructed AFTER SSAO2RenderingPipeline (PrePassRenderer must exist).
 *
 * Usage:
 *   const pp = new BilateralNormalSmoothPostProcess(scene, camera, 0.65);
 *   pp.enabled  = false;  // toggle at runtime
 *   pp.strength = 0.4;    // tune at runtime
 *   pp.dispose();         // cleanup on scene change
 */
export declare class BilateralNormalSmoothPostProcess {
    private readonly _pp;
    private readonly _camera;
    private _strength;
    private _enabled;
    private _disposed;
    constructor(scene: Scene, camera: Camera, strength?: number);
    get enabled(): boolean;
    set enabled(value: boolean);
    get strength(): number;
    set strength(value: number);
    dispose(): void;
}
