import { PostProcess } from "@babylonjs/core/PostProcesses/postProcess";
import { Effect } from "@babylonjs/core/Materials/effect";
import { Constants } from "@babylonjs/core/Engines/constants";
import type { Camera } from "@babylonjs/core/Cameras/camera";
import type { Scene } from "@babylonjs/core/scene";

const SHADER_NAME = "dve_bilateralNormSmooth";

// SE-02: Screen-space bilateral normal filter.
// Reads the PrePassRenderer normal (type 6) and depth (type 5) buffers that
// SSAO2 already forces into existence, so there is zero additional G-buffer cost.
// For each pixel it:
//   1. Detects cube face boundaries via 3×3 normal divergence weighted by depth proximity.
//   2. At boundary pixels applies a 5×5 bilateral blur: Gaussian spatial weight ×
//      tight normal match (power=8) × depth proximity.
//   3. Mixes the bilateral result into the original colour by edgeness × strength.
// Net effect: hard lighting transitions between adjacent voxel cube faces are
// softened while flat-face texture detail is left untouched.
Effect.ShadersStore[`${SHADER_NAME}FragmentShader`] = /* glsl */ `
  precision highp float;
  varying vec2 vUV;

  uniform sampler2D textureSampler;
  uniform sampler2D dve_bnNormal;
  uniform sampler2D dve_bnDepth;
  uniform vec2  dve_bnTexel;
  uniform float dve_bnStrength;

  void main(void) {
    vec4 centerColor  = texture2D(textureSampler, vUV);
    vec4 normalSample = texture2D(dve_bnNormal,   vUV);

    // Skip background / sky: these pixels have no geometry normal written.
    if (dot(normalSample.xyz, normalSample.xyz) < 0.01) {
      gl_FragColor = centerColor;
      return;
    }

    vec3  centerNorm  = normalize(normalSample.xyz);
    float centerDepth = texture2D(dve_bnDepth, vUV).r;

    // ---- Edge detection (3×3) ----------------------------------------
    // Accumulate maximum normal divergence among neighbors that sit at the
    // same depth (= same continuous surface, different face orientation).
    float maxEdge = 0.0;
    for (int dx = -1; dx <= 1; dx++) {
      for (int dy = -1; dy <= 1; dy++) {
        if (dx == 0 && dy == 0) continue;
        vec2  sUV      = vUV + vec2(float(dx), float(dy)) * dve_bnTexel;
        vec3  sn_raw   = texture2D(dve_bnNormal, sUV).xyz;
        // BUG-C01: skip sky/background neighbors — their normal is vec3(0) and
        // normalize(vec3(0)) is undefined in GLSL ES 3.0. Without this guard,
        // geometry pixels on the silhouette against the sky get edgeness=1.0
        // producing a visible smear artefact along all horizon contours.
        if (dot(sn_raw, sn_raw) < 0.01) continue;
        vec3  sn       = normalize(sn_raw);
        float sd       = texture2D(dve_bnDepth, sUV).r;
        float depthSim = exp(-abs(centerDepth - sd) * 1.0);
        float normDiff = 1.0 - dot(centerNorm, sn);
        maxEdge = max(maxEdge, normDiff * depthSim);
      }
    }

    // edgeness: 0 = interior face pixel, 1 = on a cube-face boundary.
    float edgeness = smoothstep(0.10, 0.60, maxEdge);
    if (edgeness < 0.005) {
      gl_FragColor = centerColor;
      return;
    }

    // ---- Bilateral 5×5 colour blend -----------------------------------
    // Gaussian spatial weight × tight normal match × depth proximity.
    // Only pixels on the same face (same normal) contribute strongly,
    // so flat-face texture sharpness is preserved.
    vec4  colorSum  = centerColor;
    float weightSum = 1.0;

    for (int dx = -2; dx <= 2; dx++) {
      for (int dy = -2; dy <= 2; dy++) {
        if (dx == 0 && dy == 0) continue;
        vec2  sUV      = vUV + vec2(float(dx), float(dy)) * dve_bnTexel;
        vec3  sn_raw   = texture2D(dve_bnNormal, sUV).xyz;
        // Skip sky neighbors — weight would be 0 anyway (normW=0) but guard
        // avoids normalize(vec3(0)) undefined behaviour.
        if (dot(sn_raw, sn_raw) < 0.01) continue;
        vec3  sn       = normalize(sn_raw);
        float sd       = texture2D(dve_bnDepth, sUV).r;
        float spatialW = exp(-float(dx * dx + dy * dy) * 0.5);
        float normW    = pow(max(0.0, dot(centerNorm, sn)), 8.0);
        float depthW   = exp(-abs(centerDepth - sd) * 1.0);
        float w        = spatialW * normW * depthW;
        colorSum  += texture2D(textureSampler, sUV) * w;
        weightSum += w;
      }
    }

    vec4 blended = colorSum / weightSum;
    gl_FragColor  = mix(centerColor, blended, edgeness * dve_bnStrength);
  }
`;

/**
 * SE-02: Screen-space bilateral normal smooth post-process.
 * Detects cube face boundaries via 3×3 normal divergence and blends colour
 * at voxel edges using a 5×5 bilateral filter weighted by normal similarity
 * and depth proximity. Reads the PrePassRenderer G-buffer generated by SSAO2
 * (zero extra G-buffer cost).
 *
 * Must be constructed AFTER SSAO2RenderingPipeline (PrePassRenderer must exist).
 *
 * Usage:
 *   const pp = new BilateralNormalSmoothPostProcess(scene, camera, 0.65);
 *   pp.enabled  = false;  // toggle at runtime
 *   pp.strength = 0.4;    // tune at runtime
 *   pp.dispose();         // cleanup on scene change
 */
export class BilateralNormalSmoothPostProcess {
  private readonly _pp: PostProcess;
  private readonly _camera: Camera;
  private _strength: number;
  private _enabled = true;
  private _disposed = false;  // BUG-B02: guard toggle/dispose races

  constructor(scene: Scene, camera: Camera, strength = 0.65) {
    this._strength = strength;
    this._camera = camera;
    // Fix 5: ratio 0.5 reduces ~88 texture reads/px → ~22 effective reads/px;
    // bilinear upscale at half-res is imperceptible for a colour-blend pass.
    this._pp = new PostProcess(
      "dve_bnSmooth",
      SHADER_NAME,
      ["dve_bnTexel", "dve_bnStrength"],
      ["dve_bnNormal", "dve_bnDepth"],
      0.5,
      camera
    );

    this._pp.onApplyObservable.add((effect) => {
      const engine = scene.getEngine();
      // BUG-B05: pass true to getRenderWidth/Height to get the canvas (full-res) size,
      // not the currently bound render-target size (which equals RT half-res when ratio=0.5).
      // Using the RT size caused the bilateral kernel to operate at 2× the intended granularity,
      // making the 5×5 blur cover ±4 real pixels instead of ±2 and bleed across voxel faces.
      effect.setFloat2(
        "dve_bnTexel",
        1.0 / engine.getRenderWidth(true),
        1.0 / engine.getRenderHeight(true)
      );
      effect.setFloat("dve_bnStrength", this._strength);

      const prePass = scene.prePassRenderer;
      if (!prePass) return;

      const rt       = prePass.getRenderTarget();
      const normIdx  = prePass.getIndex(Constants.PREPASS_NORMAL_TEXTURE_TYPE);
      const depthIdx = prePass.getIndex(Constants.PREPASS_DEPTH_TEXTURE_TYPE);

      if (normIdx  >= 0) effect.setTexture("dve_bnNormal", rt.textures[normIdx]);
      if (depthIdx >= 0) effect.setTexture("dve_bnDepth",  rt.textures[depthIdx]);
    });
  }

  get enabled(): boolean {
    return this._enabled;
  }
  set enabled(value: boolean) {
    if (this._disposed || this._enabled === value) return;
    this._enabled = value;
    if (value) {
      this._camera.attachPostProcess(this._pp);
    } else {
      this._camera.detachPostProcess(this._pp);
    }
  }

  get strength(): number {
    return this._strength;
  }
  set strength(value: number) {
    this._strength = value;
  }

  dispose(): void {
    if (this._disposed) return;
    this._disposed = true;
    this._pp.dispose();
  }
}
